version: '1.0'

volumes:
  postgres_data:

services:
  postgres:
      image: postgres:15.4
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: W0nder@1313
  keycloak:
      image: asi309/keycloak:1.0
      environment:
        # DB_VENDOR: POSTGRES
        # DB_ADDR: postgres
        # DB_DATABASE: keycloak
        # DB_USER: keycloak
        # DB_SCHEMA: public
        # DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: W0nder@1313
      ports:
        - 8080:8080
      depends_on:
        - postgres